### ISSUE TITLE
Open sourcing checklist

### ISSUE THREAD

**Issue by belemaire** [electrode-io/livebundle#43]
This issue contains a checklist of things to do prior to making the repository public.

## To be done just before making repository public 

- [x] Regenerate [Codecov](https://codecov.io/) token 
- [x] Revert the changes introduced in https://github.com/electrode-io/livebundle/pull/39
- [x] Delete all tags _(tags cleanup)_ so that we only have `1.0.0` release tag on open source day
